version: '3.7'

volumes:
  db_data:


x-shared_environment:
  &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password

services:
  app:
    image: ghcr.io/kevinzhow/micro-blog-demo:v0.0.2
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080"
      ]
  migrate:
    image: ghcr.io/kevinzhow/micro-blog-demo:v0.0.2
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: [ "migrate", "--yes" ]
    deploy:
      replicas: 0
  revert:
    image: ghcr.io/kevinzhow/micro-blog-demo:v0.0.2
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: [ "migrate", "--revert", "--yes" ]
    deploy:
      replicas: 0
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'
